/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedEnviadoRouteImport } from './routes/_authenticated/enviado'
import { Route as AuthenticatedEnviarRouteImport } from './routes/_authenticated/enviar'
import { Route as AuthenticatedEnviosRouteImport } from './routes/_authenticated/envios'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedEnviosIdRouteImport } from './routes/_authenticated/envios.$id'
import { Route as AuthenticatedPerfilEditarRouteImport } from './routes/_authenticated/perfil.editar'
import { Route as AuthenticatedPerfilSenhaRouteImport } from './routes/_authenticated/perfil.senha'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEnviadoRoute = AuthenticatedEnviadoRouteImport.update({
  id: '/enviado',
  path: '/enviado',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnviarRoute = AuthenticatedEnviarRouteImport.update({
  id: '/enviar',
  path: '/enviar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnviosRoute = AuthenticatedEnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnviosIdRoute = AuthenticatedEnviosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedEnviosRoute,
} as any)
const AuthenticatedPerfilEditarRoute =
  AuthenticatedPerfilEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedPerfilRoute,
  } as any)
const AuthenticatedPerfilSenhaRoute =
  AuthenticatedPerfilSenhaRouteImport.update({
    id: '/senha',
    path: '/senha',
    getParentRoute: () => AuthenticatedPerfilRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/enviado': typeof AuthenticatedEnviadoRoute
  '/enviar': typeof AuthenticatedEnviarRoute
  '/envios': typeof AuthenticatedEnviosRouteWithChildren
  '/inicio': typeof AuthenticatedInicioRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/envios/$id': typeof AuthenticatedEnviosIdRoute
  '/perfil/editar': typeof AuthenticatedPerfilEditarRoute
  '/perfil/senha': typeof AuthenticatedPerfilSenhaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/enviado': typeof AuthenticatedEnviadoRoute
  '/enviar': typeof AuthenticatedEnviarRoute
  '/envios': typeof AuthenticatedEnviosRouteWithChildren
  '/inicio': typeof AuthenticatedInicioRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/envios/$id': typeof AuthenticatedEnviosIdRoute
  '/perfil/editar': typeof AuthenticatedPerfilEditarRoute
  '/perfil/senha': typeof AuthenticatedPerfilSenhaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/enviado': typeof AuthenticatedEnviadoRoute
  '/_authenticated/enviar': typeof AuthenticatedEnviarRoute
  '/_authenticated/envios': typeof AuthenticatedEnviosRouteWithChildren
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/_authenticated/envios/$id': typeof AuthenticatedEnviosIdRoute
  '/_authenticated/perfil/editar': typeof AuthenticatedPerfilEditarRoute
  '/_authenticated/perfil/senha': typeof AuthenticatedPerfilSenhaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/enviado'
    | '/enviar'
    | '/envios'
    | '/inicio'
    | '/notificacoes'
    | '/perfil'
    | '/envios/$id'
    | '/perfil/editar'
    | '/perfil/senha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/enviado'
    | '/enviar'
    | '/envios'
    | '/inicio'
    | '/notificacoes'
    | '/perfil'
    | '/envios/$id'
    | '/perfil/editar'
    | '/perfil/senha'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/enviado'
    | '/_authenticated/enviar'
    | '/_authenticated/envios'
    | '/_authenticated/inicio'
    | '/_authenticated/notificacoes'
    | '/_authenticated/perfil'
    | '/_authenticated/envios/$id'
    | '/_authenticated/perfil/editar'
    | '/_authenticated/perfil/senha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/enviado': {
      id: '/_authenticated/enviado'
      path: '/enviado'
      fullPath: '/enviado'
      preLoaderRoute: typeof AuthenticatedEnviadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enviar': {
      id: '/_authenticated/enviar'
      path: '/enviar'
      fullPath: '/enviar'
      preLoaderRoute: typeof AuthenticatedEnviarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/envios': {
      id: '/_authenticated/envios'
      path: '/envios'
      fullPath: '/envios'
      preLoaderRoute: typeof AuthenticatedEnviosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/envios/$id': {
      id: '/_authenticated/envios/$id'
      path: '/$id'
      fullPath: '/envios/$id'
      preLoaderRoute: typeof AuthenticatedEnviosIdRouteImport
      parentRoute: typeof AuthenticatedEnviosRoute
    }
    '/_authenticated/perfil/editar': {
      id: '/_authenticated/perfil/editar'
      path: '/editar'
      fullPath: '/perfil/editar'
      preLoaderRoute: typeof AuthenticatedPerfilEditarRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
    '/_authenticated/perfil/senha': {
      id: '/_authenticated/perfil/senha'
      path: '/senha'
      fullPath: '/perfil/senha'
      preLoaderRoute: typeof AuthenticatedPerfilSenhaRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
  }
}

interface AuthenticatedEnviosRouteChildren {
  AuthenticatedEnviosIdRoute: typeof AuthenticatedEnviosIdRoute
}

const AuthenticatedEnviosRouteChildren: AuthenticatedEnviosRouteChildren = {
  AuthenticatedEnviosIdRoute: AuthenticatedEnviosIdRoute,
}

const AuthenticatedEnviosRouteWithChildren =
  AuthenticatedEnviosRoute._addFileChildren(AuthenticatedEnviosRouteChildren)

interface AuthenticatedPerfilRouteChildren {
  AuthenticatedPerfilEditarRoute: typeof AuthenticatedPerfilEditarRoute
  AuthenticatedPerfilSenhaRoute: typeof AuthenticatedPerfilSenhaRoute
}

const AuthenticatedPerfilRouteChildren: AuthenticatedPerfilRouteChildren = {
  AuthenticatedPerfilEditarRoute: AuthenticatedPerfilEditarRoute,
  AuthenticatedPerfilSenhaRoute: AuthenticatedPerfilSenhaRoute,
}

const AuthenticatedPerfilRouteWithChildren =
  AuthenticatedPerfilRoute._addFileChildren(AuthenticatedPerfilRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEnviadoRoute: typeof AuthenticatedEnviadoRoute
  AuthenticatedEnviarRoute: typeof AuthenticatedEnviarRoute
  AuthenticatedEnviosRoute: typeof AuthenticatedEnviosRouteWithChildren
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEnviadoRoute: AuthenticatedEnviadoRoute,
  AuthenticatedEnviarRoute: AuthenticatedEnviarRoute,
  AuthenticatedEnviosRoute: AuthenticatedEnviosRouteWithChildren,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
