/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedEnviadoRouteImport } from './routes/_authenticated/enviado'
import { Route as AuthenticatedEnviarRouteImport } from './routes/_authenticated/enviar'
import { Route as AuthenticatedEnviosRouteImport } from './routes/_authenticated/envios'
import { Route as AuthenticatedIdentidadeRouteImport } from './routes/_authenticated/identidade'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedTrabalhosRouteImport } from './routes/_authenticated/trabalhos'
import { Route as AuthenticatedAdminIdRouteImport } from './routes/_authenticated/admin.$id'
import { Route as AuthenticatedAdminAnunciosRouteImport } from './routes/_authenticated/admin.anuncios'
import { Route as AuthenticatedAdminIdentidadeRouteImport } from './routes/_authenticated/admin.identidade'
import { Route as AuthenticatedAdminNotificacoesRouteImport } from './routes/_authenticated/admin.notificacoes'
import { Route as AuthenticatedAdminRetiradasRouteImport } from './routes/_authenticated/admin.retiradas'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedComercianteIndexRouteImport } from './routes/_authenticated/comerciante.index'
import { Route as AuthenticatedComercianteCarteiraRouteImport } from './routes/_authenticated/comerciante.carteira'
import { Route as AuthenticatedComercianteCriarTarefaRouteImport } from './routes/_authenticated/comerciante.criar-tarefa'
import { Route as AuthenticatedComercianteMinhasTarefasRouteImport } from './routes/_authenticated/comerciante.minhas-tarefas'
import { Route as AuthenticatedComercianteRelatoriosRouteImport } from './routes/_authenticated/comerciante.relatorios'
import { Route as AuthenticatedComercianteResultadosRouteImport } from './routes/_authenticated/comerciante.resultados'
import { Route as AuthenticatedComercianteSuporteRouteImport } from './routes/_authenticated/comerciante.suporte'
import { Route as AuthenticatedEnviosIdRouteImport } from './routes/_authenticated/envios.$id'
import { Route as AuthenticatedPerfilEditarRouteImport } from './routes/_authenticated/perfil.editar'
import { Route as AuthenticatedPerfilSenhaRouteImport } from './routes/_authenticated/perfil.senha'
import { Route as AuthenticatedTrabalhosIdRouteImport } from './routes/_authenticated/trabalhos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnviadoRoute = AuthenticatedEnviadoRouteImport.update({
  id: '/enviado',
  path: '/enviado',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnviarRoute = AuthenticatedEnviarRouteImport.update({
  id: '/enviar',
  path: '/enviar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnviosRoute = AuthenticatedEnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdentidadeRoute = AuthenticatedIdentidadeRouteImport.update({
  id: '/identidade',
  path: '/identidade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrabalhosRoute = AuthenticatedTrabalhosRouteImport.update({
  id: '/trabalhos',
  path: '/trabalhos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIdRoute = AuthenticatedAdminIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnunciosRoute =
  AuthenticatedAdminAnunciosRouteImport.update({
    id: '/anuncios',
    path: '/anuncios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIdentidadeRoute =
  AuthenticatedAdminIdentidadeRouteImport.update({
    id: '/identidade',
    path: '/identidade',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificacoesRoute =
  AuthenticatedAdminNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRetiradasRoute =
  AuthenticatedAdminRetiradasRouteImport.update({
    id: '/retiradas',
    path: '/retiradas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedComercianteIndexRoute =
  AuthenticatedComercianteIndexRouteImport.update({
    id: '/comerciante/',
    path: '/comerciante/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComercianteCarteiraRoute =
  AuthenticatedComercianteCarteiraRouteImport.update({
    id: '/comerciante/carteira',
    path: '/comerciante/carteira',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComercianteCriarTarefaRoute =
  AuthenticatedComercianteCriarTarefaRouteImport.update({
    id: '/comerciante/criar-tarefa',
    path: '/comerciante/criar-tarefa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComercianteMinhasTarefasRoute =
  AuthenticatedComercianteMinhasTarefasRouteImport.update({
    id: '/comerciante/minhas-tarefas',
    path: '/comerciante/minhas-tarefas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComercianteRelatoriosRoute =
  AuthenticatedComercianteRelatoriosRouteImport.update({
    id: '/comerciante/relatorios',
    path: '/comerciante/relatorios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComercianteResultadosRoute =
  AuthenticatedComercianteResultadosRouteImport.update({
    id: '/comerciante/resultados',
    path: '/comerciante/resultados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComercianteSuporteRoute =
  AuthenticatedComercianteSuporteRouteImport.update({
    id: '/comerciante/suporte',
    path: '/comerciante/suporte',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnviosIdRoute = AuthenticatedEnviosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedEnviosRoute,
} as any)
const AuthenticatedPerfilEditarRoute =
  AuthenticatedPerfilEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedPerfilRoute,
  } as any)
const AuthenticatedPerfilSenhaRoute =
  AuthenticatedPerfilSenhaRouteImport.update({
    id: '/senha',
    path: '/senha',
    getParentRoute: () => AuthenticatedPerfilRoute,
  } as any)
const AuthenticatedTrabalhosIdRoute =
  AuthenticatedTrabalhosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedTrabalhosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/enviado': typeof AuthenticatedEnviadoRoute
  '/enviar': typeof AuthenticatedEnviarRoute
  '/envios': typeof AuthenticatedEnviosRouteWithChildren
  '/identidade': typeof AuthenticatedIdentidadeRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/trabalhos': typeof AuthenticatedTrabalhosRouteWithChildren
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/identidade': typeof AuthenticatedAdminIdentidadeRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/retiradas': typeof AuthenticatedAdminRetiradasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/comerciante/carteira': typeof AuthenticatedComercianteCarteiraRoute
  '/comerciante/criar-tarefa': typeof AuthenticatedComercianteCriarTarefaRoute
  '/comerciante/minhas-tarefas': typeof AuthenticatedComercianteMinhasTarefasRoute
  '/comerciante/relatorios': typeof AuthenticatedComercianteRelatoriosRoute
  '/comerciante/resultados': typeof AuthenticatedComercianteResultadosRoute
  '/comerciante/suporte': typeof AuthenticatedComercianteSuporteRoute
  '/envios/$id': typeof AuthenticatedEnviosIdRoute
  '/perfil/editar': typeof AuthenticatedPerfilEditarRoute
  '/perfil/senha': typeof AuthenticatedPerfilSenhaRoute
  '/trabalhos/$id': typeof AuthenticatedTrabalhosIdRoute
  '/comerciante/': typeof AuthenticatedComercianteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/enviado': typeof AuthenticatedEnviadoRoute
  '/enviar': typeof AuthenticatedEnviarRoute
  '/envios': typeof AuthenticatedEnviosRouteWithChildren
  '/identidade': typeof AuthenticatedIdentidadeRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/trabalhos': typeof AuthenticatedTrabalhosRouteWithChildren
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/identidade': typeof AuthenticatedAdminIdentidadeRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/retiradas': typeof AuthenticatedAdminRetiradasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/comerciante/carteira': typeof AuthenticatedComercianteCarteiraRoute
  '/comerciante/criar-tarefa': typeof AuthenticatedComercianteCriarTarefaRoute
  '/comerciante/minhas-tarefas': typeof AuthenticatedComercianteMinhasTarefasRoute
  '/comerciante/relatorios': typeof AuthenticatedComercianteRelatoriosRoute
  '/comerciante/resultados': typeof AuthenticatedComercianteResultadosRoute
  '/comerciante/suporte': typeof AuthenticatedComercianteSuporteRoute
  '/envios/$id': typeof AuthenticatedEnviosIdRoute
  '/perfil/editar': typeof AuthenticatedPerfilEditarRoute
  '/perfil/senha': typeof AuthenticatedPerfilSenhaRoute
  '/trabalhos/$id': typeof AuthenticatedTrabalhosIdRoute
  '/comerciante': typeof AuthenticatedComercianteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/enviado': typeof AuthenticatedEnviadoRoute
  '/_authenticated/enviar': typeof AuthenticatedEnviarRoute
  '/_authenticated/envios': typeof AuthenticatedEnviosRouteWithChildren
  '/_authenticated/identidade': typeof AuthenticatedIdentidadeRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/_authenticated/trabalhos': typeof AuthenticatedTrabalhosRouteWithChildren
  '/_authenticated/admin/$id': typeof AuthenticatedAdminIdRoute
  '/_authenticated/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/_authenticated/admin/identidade': typeof AuthenticatedAdminIdentidadeRoute
  '/_authenticated/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/_authenticated/admin/retiradas': typeof AuthenticatedAdminRetiradasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/comerciante/carteira': typeof AuthenticatedComercianteCarteiraRoute
  '/_authenticated/comerciante/criar-tarefa': typeof AuthenticatedComercianteCriarTarefaRoute
  '/_authenticated/comerciante/minhas-tarefas': typeof AuthenticatedComercianteMinhasTarefasRoute
  '/_authenticated/comerciante/relatorios': typeof AuthenticatedComercianteRelatoriosRoute
  '/_authenticated/comerciante/resultados': typeof AuthenticatedComercianteResultadosRoute
  '/_authenticated/comerciante/suporte': typeof AuthenticatedComercianteSuporteRoute
  '/_authenticated/envios/$id': typeof AuthenticatedEnviosIdRoute
  '/_authenticated/perfil/editar': typeof AuthenticatedPerfilEditarRoute
  '/_authenticated/perfil/senha': typeof AuthenticatedPerfilSenhaRoute
  '/_authenticated/trabalhos/$id': typeof AuthenticatedTrabalhosIdRoute
  '/_authenticated/comerciante/': typeof AuthenticatedComercianteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/admin'
    | '/enviado'
    | '/enviar'
    | '/envios'
    | '/identidade'
    | '/inicio'
    | '/notificacoes'
    | '/perfil'
    | '/trabalhos'
    | '/admin/$id'
    | '/admin/anuncios'
    | '/admin/identidade'
    | '/admin/notificacoes'
    | '/admin/retiradas'
    | '/admin/usuarios'
    | '/comerciante/carteira'
    | '/comerciante/criar-tarefa'
    | '/comerciante/minhas-tarefas'
    | '/comerciante/relatorios'
    | '/comerciante/resultados'
    | '/comerciante/suporte'
    | '/envios/$id'
    | '/perfil/editar'
    | '/perfil/senha'
    | '/trabalhos/$id'
    | '/comerciante/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/admin'
    | '/enviado'
    | '/enviar'
    | '/envios'
    | '/identidade'
    | '/inicio'
    | '/notificacoes'
    | '/perfil'
    | '/trabalhos'
    | '/admin/$id'
    | '/admin/anuncios'
    | '/admin/identidade'
    | '/admin/notificacoes'
    | '/admin/retiradas'
    | '/admin/usuarios'
    | '/comerciante/carteira'
    | '/comerciante/criar-tarefa'
    | '/comerciante/minhas-tarefas'
    | '/comerciante/relatorios'
    | '/comerciante/resultados'
    | '/comerciante/suporte'
    | '/envios/$id'
    | '/perfil/editar'
    | '/perfil/senha'
    | '/trabalhos/$id'
    | '/comerciante'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/enviado'
    | '/_authenticated/enviar'
    | '/_authenticated/envios'
    | '/_authenticated/identidade'
    | '/_authenticated/inicio'
    | '/_authenticated/notificacoes'
    | '/_authenticated/perfil'
    | '/_authenticated/trabalhos'
    | '/_authenticated/admin/$id'
    | '/_authenticated/admin/anuncios'
    | '/_authenticated/admin/identidade'
    | '/_authenticated/admin/notificacoes'
    | '/_authenticated/admin/retiradas'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/comerciante/carteira'
    | '/_authenticated/comerciante/criar-tarefa'
    | '/_authenticated/comerciante/minhas-tarefas'
    | '/_authenticated/comerciante/relatorios'
    | '/_authenticated/comerciante/resultados'
    | '/_authenticated/comerciante/suporte'
    | '/_authenticated/envios/$id'
    | '/_authenticated/perfil/editar'
    | '/_authenticated/perfil/senha'
    | '/_authenticated/trabalhos/$id'
    | '/_authenticated/comerciante/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enviado': {
      id: '/_authenticated/enviado'
      path: '/enviado'
      fullPath: '/enviado'
      preLoaderRoute: typeof AuthenticatedEnviadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enviar': {
      id: '/_authenticated/enviar'
      path: '/enviar'
      fullPath: '/enviar'
      preLoaderRoute: typeof AuthenticatedEnviarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/envios': {
      id: '/_authenticated/envios'
      path: '/envios'
      fullPath: '/envios'
      preLoaderRoute: typeof AuthenticatedEnviosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/identidade': {
      id: '/_authenticated/identidade'
      path: '/identidade'
      fullPath: '/identidade'
      preLoaderRoute: typeof AuthenticatedIdentidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trabalhos': {
      id: '/_authenticated/trabalhos'
      path: '/trabalhos'
      fullPath: '/trabalhos'
      preLoaderRoute: typeof AuthenticatedTrabalhosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$id': {
      id: '/_authenticated/admin/$id'
      path: '/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AuthenticatedAdminIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/anuncios': {
      id: '/_authenticated/admin/anuncios'
      path: '/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AuthenticatedAdminAnunciosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/identidade': {
      id: '/_authenticated/admin/identidade'
      path: '/identidade'
      fullPath: '/admin/identidade'
      preLoaderRoute: typeof AuthenticatedAdminIdentidadeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notificacoes': {
      id: '/_authenticated/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AuthenticatedAdminNotificacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/retiradas': {
      id: '/_authenticated/admin/retiradas'
      path: '/retiradas'
      fullPath: '/admin/retiradas'
      preLoaderRoute: typeof AuthenticatedAdminRetiradasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/comerciante/': {
      id: '/_authenticated/comerciante/'
      path: '/comerciante'
      fullPath: '/comerciante/'
      preLoaderRoute: typeof AuthenticatedComercianteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comerciante/carteira': {
      id: '/_authenticated/comerciante/carteira'
      path: '/comerciante/carteira'
      fullPath: '/comerciante/carteira'
      preLoaderRoute: typeof AuthenticatedComercianteCarteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comerciante/criar-tarefa': {
      id: '/_authenticated/comerciante/criar-tarefa'
      path: '/comerciante/criar-tarefa'
      fullPath: '/comerciante/criar-tarefa'
      preLoaderRoute: typeof AuthenticatedComercianteCriarTarefaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comerciante/minhas-tarefas': {
      id: '/_authenticated/comerciante/minhas-tarefas'
      path: '/comerciante/minhas-tarefas'
      fullPath: '/comerciante/minhas-tarefas'
      preLoaderRoute: typeof AuthenticatedComercianteMinhasTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comerciante/relatorios': {
      id: '/_authenticated/comerciante/relatorios'
      path: '/comerciante/relatorios'
      fullPath: '/comerciante/relatorios'
      preLoaderRoute: typeof AuthenticatedComercianteRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comerciante/resultados': {
      id: '/_authenticated/comerciante/resultados'
      path: '/comerciante/resultados'
      fullPath: '/comerciante/resultados'
      preLoaderRoute: typeof AuthenticatedComercianteResultadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comerciante/suporte': {
      id: '/_authenticated/comerciante/suporte'
      path: '/comerciante/suporte'
      fullPath: '/comerciante/suporte'
      preLoaderRoute: typeof AuthenticatedComercianteSuporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/envios/$id': {
      id: '/_authenticated/envios/$id'
      path: '/$id'
      fullPath: '/envios/$id'
      preLoaderRoute: typeof AuthenticatedEnviosIdRouteImport
      parentRoute: typeof AuthenticatedEnviosRoute
    }
    '/_authenticated/perfil/editar': {
      id: '/_authenticated/perfil/editar'
      path: '/editar'
      fullPath: '/perfil/editar'
      preLoaderRoute: typeof AuthenticatedPerfilEditarRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
    '/_authenticated/perfil/senha': {
      id: '/_authenticated/perfil/senha'
      path: '/senha'
      fullPath: '/perfil/senha'
      preLoaderRoute: typeof AuthenticatedPerfilSenhaRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
    '/_authenticated/trabalhos/$id': {
      id: '/_authenticated/trabalhos/$id'
      path: '/$id'
      fullPath: '/trabalhos/$id'
      preLoaderRoute: typeof AuthenticatedTrabalhosIdRouteImport
      parentRoute: typeof AuthenticatedTrabalhosRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIdRoute: typeof AuthenticatedAdminIdRoute
  AuthenticatedAdminAnunciosRoute: typeof AuthenticatedAdminAnunciosRoute
  AuthenticatedAdminIdentidadeRoute: typeof AuthenticatedAdminIdentidadeRoute
  AuthenticatedAdminNotificacoesRoute: typeof AuthenticatedAdminNotificacoesRoute
  AuthenticatedAdminRetiradasRoute: typeof AuthenticatedAdminRetiradasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIdRoute: AuthenticatedAdminIdRoute,
  AuthenticatedAdminAnunciosRoute: AuthenticatedAdminAnunciosRoute,
  AuthenticatedAdminIdentidadeRoute: AuthenticatedAdminIdentidadeRoute,
  AuthenticatedAdminNotificacoesRoute: AuthenticatedAdminNotificacoesRoute,
  AuthenticatedAdminRetiradasRoute: AuthenticatedAdminRetiradasRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedEnviosRouteChildren {
  AuthenticatedEnviosIdRoute: typeof AuthenticatedEnviosIdRoute
}

const AuthenticatedEnviosRouteChildren: AuthenticatedEnviosRouteChildren = {
  AuthenticatedEnviosIdRoute: AuthenticatedEnviosIdRoute,
}

const AuthenticatedEnviosRouteWithChildren =
  AuthenticatedEnviosRoute._addFileChildren(AuthenticatedEnviosRouteChildren)

interface AuthenticatedPerfilRouteChildren {
  AuthenticatedPerfilEditarRoute: typeof AuthenticatedPerfilEditarRoute
  AuthenticatedPerfilSenhaRoute: typeof AuthenticatedPerfilSenhaRoute
}

const AuthenticatedPerfilRouteChildren: AuthenticatedPerfilRouteChildren = {
  AuthenticatedPerfilEditarRoute: AuthenticatedPerfilEditarRoute,
  AuthenticatedPerfilSenhaRoute: AuthenticatedPerfilSenhaRoute,
}

const AuthenticatedPerfilRouteWithChildren =
  AuthenticatedPerfilRoute._addFileChildren(AuthenticatedPerfilRouteChildren)

interface AuthenticatedTrabalhosRouteChildren {
  AuthenticatedTrabalhosIdRoute: typeof AuthenticatedTrabalhosIdRoute
}

const AuthenticatedTrabalhosRouteChildren: AuthenticatedTrabalhosRouteChildren =
  {
    AuthenticatedTrabalhosIdRoute: AuthenticatedTrabalhosIdRoute,
  }

const AuthenticatedTrabalhosRouteWithChildren =
  AuthenticatedTrabalhosRoute._addFileChildren(
    AuthenticatedTrabalhosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedEnviadoRoute: typeof AuthenticatedEnviadoRoute
  AuthenticatedEnviarRoute: typeof AuthenticatedEnviarRoute
  AuthenticatedEnviosRoute: typeof AuthenticatedEnviosRouteWithChildren
  AuthenticatedIdentidadeRoute: typeof AuthenticatedIdentidadeRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRouteWithChildren
  AuthenticatedTrabalhosRoute: typeof AuthenticatedTrabalhosRouteWithChildren
  AuthenticatedComercianteCarteiraRoute: typeof AuthenticatedComercianteCarteiraRoute
  AuthenticatedComercianteCriarTarefaRoute: typeof AuthenticatedComercianteCriarTarefaRoute
  AuthenticatedComercianteMinhasTarefasRoute: typeof AuthenticatedComercianteMinhasTarefasRoute
  AuthenticatedComercianteRelatoriosRoute: typeof AuthenticatedComercianteRelatoriosRoute
  AuthenticatedComercianteResultadosRoute: typeof AuthenticatedComercianteResultadosRoute
  AuthenticatedComercianteSuporteRoute: typeof AuthenticatedComercianteSuporteRoute
  AuthenticatedComercianteIndexRoute: typeof AuthenticatedComercianteIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedEnviadoRoute: AuthenticatedEnviadoRoute,
  AuthenticatedEnviarRoute: AuthenticatedEnviarRoute,
  AuthenticatedEnviosRoute: AuthenticatedEnviosRouteWithChildren,
  AuthenticatedIdentidadeRoute: AuthenticatedIdentidadeRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRouteWithChildren,
  AuthenticatedTrabalhosRoute: AuthenticatedTrabalhosRouteWithChildren,
  AuthenticatedComercianteCarteiraRoute: AuthenticatedComercianteCarteiraRoute,
  AuthenticatedComercianteCriarTarefaRoute:
    AuthenticatedComercianteCriarTarefaRoute,
  AuthenticatedComercianteMinhasTarefasRoute:
    AuthenticatedComercianteMinhasTarefasRoute,
  AuthenticatedComercianteRelatoriosRoute:
    AuthenticatedComercianteRelatoriosRoute,
  AuthenticatedComercianteResultadosRoute:
    AuthenticatedComercianteResultadosRoute,
  AuthenticatedComercianteSuporteRoute: AuthenticatedComercianteSuporteRoute,
  AuthenticatedComercianteIndexRoute: AuthenticatedComercianteIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
